#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # bootstrap functions for customizations
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox" # g:spacevim_colorscheme # molokai  
    # 'gruvbox', 'molokai', 'onedark', 'jellybeans', 'one', 'nord', 'hybrid', 'NeoSolarized', 'material', 'srcery',
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    enable_statusline_mode = false
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'filename',
       'major mode',
       'syntax checking'
       'minor mode lighters',
       'version control info',
    ]
    # right sections of statusline
    statusline_right_sections = [
       'fileformat', 
       'cursorpos',
       'date',
       'time'
       'percentage',
    ]
    # 'winnr' window number
    # 'syntax checking'
    # 'filename' file name
    # 'fileformat' file format
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' cursor position
    # 'percentage' content range
    # 'date' date
    # 'time' time
    # 'whitespace' line number with trailing space at the end
    # 'battery status' battery status
    # 'input method' input method
    # 'search status' search index
    # buffer_index_type = 0 # 4
    # windows_index_type = 1 # 3
    enable_os_fileformat_icon = true
    # enable_tabline_ft_icon = true
    enable_vimfiler_gitstatus = true
    enable_vimfiler_filetypeicon = true

    filemanager = "nerdtree" 
    filetree_direction = "left"
    project_rooter_patterns = ['.project','.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
    # The , key does repeat last f, F, t and T in vim, but in SpaceVim it is the language specified Leader key. 
    # To disable this feature, set the option enable_language_specific_leader to false.
    enable_language_specific_leader = false
    enable_statusline_tag = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippets_in_popup = true

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/core.vim
[[layers]]
    name = 'core'
    filetree_show_hidden = true

# https://spacevim.org/layers/fzf/
[[layers]]
  name = "fzf"

# https://spacevim.org/layers/leaderf/
# https://github.com/Yggdroot/LeaderF
[[layers]]
  name = "leaderf"
  
# https://spacevim.org/layers/ctrlp/
#[[layers]]
#  name = "ctrlp"

# https://spacevim.org/layers/unite/
#[[layers]]
#  name = "unite"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "fugitive" #gina

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "checkers"

# https://spacevim.org/layers/edit/
[[layers]]
  name = "edit"

# https://spacevim.org/layers/core/statusline/
[[layers]]
  name = "core#statusline" 
  enable = false

# https://spacevim.org/layers/core/tabline/
[[layers]]
  name = "core#tabline"

# https://spacevim.org/layers/ui/
# https://github.com/majutsushi/tagbar
# https://github.com/mhinz/vim-startify
# https://github.com/Yggdroot/indentLine
[[layers]]
  name = "ui"
  enable_sidebar = false # merges vimfiller with tagbar

# https://github.com/ryanoasis/vim-devicons
[[custom_plugins]]
  name = 'ryanoasis/vim-devicons'
  merged = false

# https://github.com/simnalamburt/vim-mundo
[[custom_plugins]]
  name = 'simnalamburt/vim-mundo'
  on_cmd = ["MundoToggle", "MundoHide", "MundoShow"] 
  merged = false

# https://github.com/jlanzarotta/bufexplorer
[[custom_plugins]]
  name = 'jlanzarotta/bufexplorer'
  on_cmd = ["ToggleBufExplorer", "BufExplorerVerticalSplit", "BufExplorerHorizontalSplit"]
  merged = false

# https://github.com/MattesGroeger/vim-bookmarks
[[custom_plugins]]
  name = 'MattesGroeger/vim-bookmarks'
  on_cmd = ['BookmarkShowAll', 'BookmarkToggle', 'BookmarkAnnotate', 'BookmarkNext', 'BookmarkPrev' ]
  merged = false

# https://github.com/junegunn/rainbow_parentheses.vim
[[custom_plugins]]
  name = 'junegunn/rainbow_parentheses.vim'
  on_cmd = ["RainbowParentheses", "RainbowParenthesesColors"]
  merged = false

# https://github.com/tpope/vim-vinegar 
[[custom_plugins]]
  name = 'tpope/vim-vinegar'
  merged = false

# https://github.com/ferhaterata/open-pdf 
#[[custom_plugins]]
#  name = 'ferhaterata/open-pdf'
#  merged = false

# https://github.com/Yggdroot/LeaderF
#[[custom_plugins]]
#  name = 'Yggdroot/LeaderF'
#  merged = false

# https://spacevim.org/layers/lang/latex/
[[layers]]
  name = "lang#latex" 

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "tmux"
# tmux_navigator_modifier = "alt"

# https://spacevim.org/layers/gtags/
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "lang#ocaml"

# https://spacevim.org/layers/github/
[[layers]]
  name = "github"

# https://spacevim.org/layers/debug/
[[layers]]
  name = "debug"

# https://spacevim.org/layers/lang/c/
[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

# https://spacevim.org/layers/lang/vim/
# https://github.com/lervag/vimtex
[[layers]]
  name = "lang#vim"

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/tools.vim
# https://github.com/junegunn/rainbow_parentheses.vim
# https://github.com/simnalamburt/vim-mundo
# https://github.com/tpope/vim-scriptease
# https://github.com/itchyny/calendar.vim
# https://github.com/junegunn/limelight.vim
# https://github.com/junegunn/goyo.vim
# https://github.com/mbbill/fencview
# https://github.com/lymslive/vimloo
# https://github.com/lymslive/vnote
#[[layers]]
#  name = "tools"

[[layers]]
  name = "tools#zeal"

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/incsearch.vim
[[layers]]
  name = "incsearch"

# https://spacevim.org/layers/language-server-protocol/
[[layers]]
  name = "lsp"
  
[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#json"
  
