#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # bootstrap functions for customizations
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "gruvbox" # g:spacevim_colorscheme # molokai  
  # colorscheme = "one" # g:spacevim_colorscheme # molokai
  # 'gruvbox', 'molokai', 'onedark', 'jellybeans', 'one', 'nord', 'hybrid', 'NeoSolarized', 'material', 'srcery',
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  enable_statusline_mode = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  # left sections of statusline
  statusline_left_sections = [
    'winnr',
    'filename',
    'major mode',
    'syntax checking'
    'minor mode lighters',
    'version control info',
  ]
  # right sections of statusline
  statusline_right_sections = [
    'fileformat', 
    'cursorpos',
    'date',
    'time'
    'percentage',
  ]
  # 'winnr' window number
    # 'syntax checking'
    # 'filename' file name
    # 'fileformat' file format
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' cursor position
    # 'percentage' content range
    # 'date' date
    # 'time' time
    # 'whitespace' line number with trailing space at the end
    # 'battery status' battery status
    # 'input method' input method
    # 'search status' search index
    # buffer_index_type = 0 # 4
    # windows_index_type = 1 # 3
    enable_os_fileformat_icon = true
    # enable_tabline_ft_icon = true
    enable_vimfiler_gitstatus = true
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_welcome = 0
    # https://github.com/SpaceVim/SpaceVim/blob/master/config/plugins/defx.vim
    # https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/core.vim
    filemanager = "defx" #"nerdtree" 
    filetree_direction = "left"
    project_rooter_patterns = ['.project','.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
    # The , key does repeat last f, F, t and T in vim, but in SpaceVim it is the language specified Leader key. 
    # To disable this feature, set the option enable_language_specific_leader to false.
    enable_language_specific_leader = false
    enable_statusline_tag = true
    disabled_plugins = ["nerdtree-git-plugin", "statusline"]
    # in order to use s for easymotion 
    windows_leader = ''
    github_username = 'ferhat.erata'
    commandline_prompt = '' #'➭'
    # enable_googlesuggest = false
    # enable_ycm = true
    error_symbol = '✗'
    autocomplete_parens = true
    autocomplete_method = "coc"
    max_column = 80
    
# bug??: https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/autocomplete.vim#L77
# defx needs the followings for vim8
[[custom_plugins]]
  name = "SpaceVim/nvim-yarp"
  merged = false

[[custom_plugins]]
  name = "SpaceVim/vim-hug-neovim-rpc"
  merged = false

# Enable autocomplete layer
# neoclide/coc
# cd ~/.cache/vimfiles/repos/github.com/neoclide/coc.nvim
# git clean -xfd
# yarn install --frozen-lockfile
# -----------
# https://github.com/neoclide/coc-sources [coc-dictionary, coc-tag, coc-word]
# https://github.com/neoclide/coc-vimtex
# https://github.com/neoclide/coc-json 
# https://github.com/fannheyward/coc-texlab
# https://github.com/fannheyward/coc-xml
# https://github.com/oncomouse/coc-bibtex
# https://github.com/neoclide/coc-tabnine
# https://github.com/neoclide/coc-prettier [JavaScript / TypeScript / CSS / JSON]
# https://github.com/neoclide/coc-java
# https://github.com/neoclide/coc-snippets
# https://github.com/clangd/coc-clangd 
# https://github.com/weirongxu/coc-explorer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_enable_snippets_in_popup = true
  auto_completion_complete_with_key_sequence = "jk"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/core.vim
[[layers]]
  name = 'core'
  filetree_show_hidden = true

# https://spacevim.org/documentation/#fuzzy-finder
# (unite, denite, leaderf, ctrlp and fzf layer)
#  
# https://spacevim.org/layers/fzf/
[[layers]]
  name = "fzf"
# https://github.com/junegunn/fzf.vim
[[custom_plugins]]
  name = "junegunn/fzf.vim"
  merged = false
# https://github.com/yuki-ycino/fzf-preview.vim
[[custom_plugins]]
  name = "yuki-ycino/fzf-preview.vim"
  merged = false
# 
# https://spacevim.org/layers/leaderf/
# https://github.com/Yggdroot/LeaderF
# https://github.com/SpaceVim/SpaceVim/blob/master/config/plugins/LeaderF.vim
[[layers]]
  name = "leaderf"
#
# https://spacevim.org/layers/denite/
# https://github.com/Shougo/denite.nvim
# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/denite.vim
#[[layers]]
#  name = "denite" 
#
#https://spacevim.org/layers/ctrlp/
# [[layers]]
#  name = "ctrlp"
#
# https://spacevim.org/layers/unite/
#[[layers]]
#  name = "unite"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "fugitive" #gina

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "checkers"

# https://spacevim.org/layers/edit/
[[layers]]
  name = "edit"

# https://spacevim.org/layers/core/statusline/
[[layers]]
  name = "core#statusline" 
  enable = false

# https://spacevim.org/layers/core/tabline/
[[layers]]
  name = "core#tabline"

# https://spacevim.org/layers/ui/
# https://github.com/majutsushi/tagbar
# https://github.com/mhinz/vim-startify
# https://github.com/SpaceVim/SpaceVim/blob/master/config/plugins/vim-startify.vim
# https://github.com/Yggdroot/indentLine
[[layers]]
  name = "ui"
  enable_sidebar = false # merges vimfiller with tagbar

# https://github.com/Xuyuanp/nerdtree-git-plugin
# [[custom_plugins]]
  # name = 'Xuyuanp/nerdtree-git-plugin'
  # merged = false

# https://github.com/ryanoasis/vim-devicons
[[custom_plugins]]
  name = 'ryanoasis/vim-devicons'
  merged = false

# https://github.com/simnalamburt/vim-mundo
[[custom_plugins]]
  name = 'simnalamburt/vim-mundo'
  on_cmd = ["MundoToggle", "MundoHide", "MundoShow"] 
  merged = false

# https://github.com/jlanzarotta/bufexplorer
[[custom_plugins]]
  name = 'jlanzarotta/bufexplorer'
  on_cmd = ["ToggleBufExplorer", "BufExplorerVerticalSplit", "BufExplorerHorizontalSplit"]
  merged = false

# https://github.com/MattesGroeger/vim-bookmarks
# [[custom_plugins]]
  # name = 'MattesGroeger/vim-bookmarks'
  # on_cmd = ['BookmarkShowAll', 'BookmarkToggle', 'BookmarkAnnotate', 'BookmarkNext', 'BookmarkPrev' ]
  # merged = false

# https://github.com/kshenoy/vim-signature 
[[custom_plugins]]
  name = 'kshenoy/vim-signature'
  merged = false

# https://github.com/junegunn/rainbow_parentheses.vim
[[custom_plugins]]
  name = 'junegunn/rainbow_parentheses.vim'
  on_cmd = ["RainbowParentheses", "RainbowParenthesesColors"]
  merged = false

# https://github.com/RRethy/vim-illuminate
[[custom_plugins]]
  name = 'RRethy/vim-illuminate'
  merged = false

# https://github.com/tpope/vim-vinegar 
# [[custom_plugins]]
  # name = 'tpope/vim-vinegar'
  # merged = false

# https://github.com/justinmk/vim-dirvish
# [[custom_plugins]]
  # name = 'justinmk/vim-dirvish'
  # merged = false

# https://github.com/kristijanhusak/vim-dirvish-git
# [[custom_plugins]]
  # name = 'kristijanhusak/vim-dirvish-git'
  # merged = false

# "https://github.com/tiagofumo/vim-nerdtree-syntax-highlight
# [[custom_plugins]]
  # name = 'tiagofumo/vim-nerdtree-syntax-highlight'
  # merged = false

# https://github.com/mg979/vim-visual-multi
[[custom_plugins]]
  name = 'mg979/vim-visual-multi'
  merged = false

# https://github.com/wincent/terminus.git
# [[custom_plugins]]
#  name = 'wincent/terminus.git'
#  merged = false

# https://github.com/bohlender/vim-smt2
[[custom_plugins]]
  name = 'bohlender/vim-smt2'
  merged = false

# https://github.com/voldikss/vim-floaterm
[[custom_plugins]]
  name = 'voldikss/vim-floaterm'
  merged = false

# https://github.com/vifm/vifm.vim
[[custom_plugins]]
  name = 'vifm/vifm.vim'
  merged = false

# https://github.com/ferhaterata/open-pdf 
#[[custom_plugins]]
#  name = 'ferhaterata/open-pdf'
#  merged = false

# https://github.com/Yggdroot/LeaderF
#[[custom_plugins]]
#  name = 'Yggdroot/LeaderF'
#  merged = false

# https://github.com/neoformat/neoformat
[[layers]]
  name = "format"

# https://spacevim.org/layers/tmux/
[[layers]]
  name = "tmux"
# tmux_navigator_modifier = "alt"

# https://spacevim.org/layers/gtags/
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

# https://spacevim.org/layers/github/
[[layers]]
  name = "github"

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/tools.vim
# https://github.com/junegunn/rainbow_parentheses.vim
# https://github.com/simnalamburt/vim-mundo
# https://github.com/tpope/vim-scriptease
# https://github.com/itchyny/calendar.vim
# https://github.com/junegunn/limelight.vim
# https://github.com/junegunn/goyo.vim
# https://github.com/mbbill/fencview
# https://github.com/lymslive/vimloo
# https://github.com/lymslive/vnote
#[[layers]]
#  name = "tools"

[[layers]]
  name = "tools#zeal"

# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/incsearch.vim
# haya14busa/incsearch.vim
# haya14busa/incsearch-fuzzy.vim
# haya14busa/vim-asterisk
# haya14busa/incsearch-easymotion.vim
# osyo-manga/vim-over
[[layers]]
  name = "incsearch"

# https://spacevim.org/layers/language-server-protocol/
# https://github.com/neoclide/coc.nvim
[[layers]]
  name = "lsp"
  filetypes = [
    # "rust", # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    "javascript", # sudo npm install -g javascript-typescript-langserver
    "sh", # sudo npm i -g bash-language-server 
    "python", #pip install --user python-language-server
#    "c", #https://clangd.llvm.org/installation.html
#    "cpp" #https://clangd.llvm.org/installation.html
  ]

# https://github.com/jackguo380/vim-lsp-cxx-highlight
[[custom_plugins]]
  name = 'jackguo380/vim-lsp-cxx-highlight'
  merged = false

# https://github.com/pboettch/vim-cmake-syntax
[[custom_plugins]]
  name = 'pboettch/vim-cmake-syntax'
  merged = false

# https://spacevim.org/layers/lang/vim/
# https://github.com/lervag/vimtex
[[layers]]
  name = "lang#vim"

# https://github.com/fannheyward/coc-xml
[[layers]]
  name = "lang#xml"

# https://github.com/neoclide/coc-json 
[[layers]]
  name = "lang#json"

# https://spacevim.org/layers/lang/java/
[[layers]]
  name = "lang#java"

# https://spacevim.org/layers/debug/
[[layers]]
  name = "debug"

# https://spacevim.org/layers/lang/c/
# https://github.com/xavierd/clang_complete (if coc is selected for autocomplete)
[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  libclang_path = "/usr/lib/llvm-6.0/lib/"
  [layer.clang_std]
    c = "c11"
    cpp = "c++17"
    objc = "c11"
    objcpp = "c++1z"

# https://spacevim.org/layers/lang/latex/
# pip install proselint # https://github.com/amperser/proselint/
# https://github.com/lervag/vimtex
# https://github.com/neoclide/coc-vimtex
# https://github.com/fannheyward/coc-texlab
# https://github.com/oncomouse/coc-bibtex
[[layers]]
  name = "lang#latex" 
  
# https://spacevim.org/layers/lang/markdown/
# https://github.com/mzlogin/vim-markdown-toc
# https://github.com/lvht/tagbar-markdown
# https://github.com/gabrielelana/vim-markdown
[[layers]]
  name = "lang#markdown"
# sudo npm -g install remark
# sudo npm -g install remark-cli
# sudo npm -g install remark-stringify
# sudo npm -g install remark-frontmatter
# sudo npm -g install wcwidth
# sudo apt install php*

# 
[[layers]]
  name = "lang#ocaml"

